s = 'A sample string'
print(len(s))
print(min(s))
print(max(s))
print('z' in s)
print('sa' in s)
print(s.count(s))
print(s.index('p'))
print(s[3:7])
print(s[4:])
print(s[:5])
print(s.isalpha())
print(s.isupper())
print(s.lower())
print(s.upper())
print(s.split())
