AAA = "Python"
BBB = "1345 Engineering"
CCC = "Sequence"
A = AAA.isupper()
print("A=",A)
B = BBB.isdigit()
print("B=",B)
C = BBB.isalnum
print("C=",C)
D = ["A", "BC"] * 2
print("D=",D)
E = CCC.lower().upper()
print("E=",E)
F = CCC.count( "e" )
print("F=",F)
G = CCC.find( "e" )
print("G=",G)
H = CCC.find("en")
print("H=",H)
J = CCC.replace( "e", "x")
print("J=",J)
