A = 3*[25]
print("A=",A)
B = 3*list( "25" )
print("B=",B)
C = 3*list( range(3) )
print("C=",C)
D = ["a"] + ["bc"]*2
print("D=",D)
E = ["A","BC"]*2
print("E=",E)
G = "a" in ["a","n","t"]
print("G=",G)
Z = ["Arthur", "King", "of", "the", "Britons"]
print("Z=",Z)
H = Z[:4]
print("H=",H)
I = Z[-3:]
print("I=",I)
J = Z[-6:-2]
print("J=",J)
K = Z[1][2]
print("K=",K)
